security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        doctrine:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # this firewall applies to all URLs
            pattern: ^/
            # denying access is done in access_control or in controllers
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                # secure the login form against CSRF
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path:  true
                default_target_path:  /
            logout_on_user_change: true
            logout:
                path: /logout
                target: /

    access_control:
        # catch-all for the admin area
        # additional security lives in the controllers
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
